type Query {
  post(id: ID!): Post
  postBySlug(slug: Slug!): Post
  posts: [Post!]!
  postRevision(id: ID!): PostRevision
}

type Mutation {
  putPost(input: PutPostInput!): Post!
  deletePost(id: ID!): DeletedEntity
}

input PutPostInput {
  id: ID
  slug: Slug
  title: NonEmptyString
  markdownContent: String
}

type DeletedPost implements DeletedEntity {
  id: ID!
}

type Post implements Entity {
  id: ID!
  slug: Slug!
  title: NonEmptyString!
  markdownContent: String!
  createdAt: DateTimeISO!
  updatedAt: DateTimeISO!
  revisions: [PostRevision!]!
}

type PostRevision implements Entity {
  id: ID!
  revisionNumber: Int!
  title: NonEmptyString!
  markdownContent: String!
  createdAt: DateTimeISO!
  post: Post!
}
